services:
  db:
    image: postgres:15
    container_name: scan2cook_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scan2cook
    ports:
      - "5435:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  backend:
    build: ./backend
    container_name: scan2cook_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/scan2cook
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - ALEXA_USER_ID=1        
    volumes:
      - ./backend/google-credentials.json:/app/google-credentials.json
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: scan2cook_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
